### ISSUE TITLE
Extensions missing from docs

### ISSUE THREAD

**Issue by magyarb** [Azure/functions-action#29]
I've tried to use the example yml file, but the deployed app did not start on azure. Inspecting the differences between the zip deployed by this action, and the zip deployed by the vscode azure functions extension, there was one difference. The bin and obj folders were missing.

The doc should include extension installation before deployment. The bin and obj folders are in the .gitignore by default, so they should be generated on deployment. The working code:

`
- name: 'Run npm'
      shell: pwsh
      run: |
        npm install
        dotnet build extensions.csproj -o bin --no-incremental
`

With this code, the action runs for 4 minutes. Maybe there is another way of installing extensions, but making the whole process faster.

**Comment by Hazhzeng** [comment]
We should not use the `dotnet` command to resolve the extensions any more, since extension bundle is now supported in host.json.
```javascript
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
```

This part is already documented in https://github.com/Azure/functions-action#create-azure-function-app-and-deploy-using-github-actions-rbac

For more information, please check https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles
