### ISSUE TITLE
Seeing `set-env` error while running my workflow with the latest version of functions-action.

### ISSUE THREAD

**Issue by MohdmM01** [Azure/functions-action#47]
I am seeing this error message while running my workflow using the latest version of this action:

Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files.

When are the new version going to be released to fix it? It seems that the action will be deprecated next week,

**Comment by aksm-ms** [comment]
@MohdmM01 Are you facing this issue while using azure/functions-action@v1? Can you please share the workflow used?

**Comment by nikkh** [comment]
I have a couple of workflows that use azure/functions-action@v1 that have stopped working in the last day or so - and I was just in the process of raising a question on stack overflow, when I saw this.  i do recall mention of set-env in the logs a few days ago but I was focusing on something else so didn't follow-up.

I have a number of applications that use this action, and as it happens they have all stopped working overnight.  I suspect they may be related to this.  There have been no other relevant changes in my repos.  Take a look at these:

[https://github.com/nikkh/heracles-ai/runs/1411302955](https://github.com/nikkh/heracles-ai/runs/1411302955?check_suite_focus=true)
[https://github.com/nikkh/heracles-ai/runs/1406173184](https://github.com/nikkh/heracles-ai/runs/1406173184?check_suite_focus=true)
[https://github.com/nikkh/zodiac/runs/1407855810](https://github.com/nikkh/zodiac/runs/1407855810?check_suite_focus=true)

This is a log from a successful run for the first failure abive:

[https://github.com/nikkh/heracles-ai/runs/1397235421](https://github.com/nikkh/heracles-ai/runs/1397235421?check_suite_focus=true)

Unfortunately, since I am mainly developing the workflows I have a cleanup job that deletes successfully deployed azure resources so I cant go back and look at (e.g.) kudo logs for successful deployments.

I'm an MS-FTE you can ping nhill to get in touch.

**Comment by aksm-ms** [comment]
Had a call with @nikkh and tried to reproduce the issue. we did not face the error set-env command deprecated.

**Comment by aksm-ms** [comment]
@MohdmM01 please confirm if you are still facing the issue

**Comment by aksm-ms** [comment]
@MohdmM01 Can you please verify if you are still facing the issue?

**Comment by MohdmM01** [comment]
I am no longer seeing the issue as this action is relying on other actions that has been updated to not use set-env. Thanks for the support.
