### ISSUE TITLE
Need func

### ISSUE THREAD

**Issue by kaihendry** [Azure/functions-action#59]
I've been studying https://github.com/Azure/functions-action/blob/master/action.yml and I was hoping that it would just install azure-functions-core-tools-bin's func, via a Dockerfile. But it doesn't.

If I just want func so that I perform a simple `func azure functionapp publish`, where do I go?

**Comment by balag0** [comment]
Could you provide more details on the scenario? Are you looking to run func commands from inside a Linux function app?

**Comment by kaihendry** [comment]
The app is here https://github.com/kaihendry/count/tree/azure-functions

I just want to be able to do a `make deploy`

**Comment by balag0** [comment]
What error are you seeing when running 
func azure functionapp publish [functionapp-name]

**Comment by kaihendry** [comment]
I have it working now, so thanks https://github.com/kaihendry/count/actions?query=branch%3Aazure-functions

**Comment by markuscodes1** [comment]
Let's reopen the issue. I came across the same problem with my nodejs project.

I have created my project with azure function core tools. This will add a script which can be used to build for production like `yarn build:production` in my nodejs case. Under the hood this script calls among others things `func extensions install`.

I think it's a little bit confusing because the example pipelines calls `npm build` and it just works but for the projects generated with the function core tools these tools must be installed to get the "build for production script" running. Maybe we should update the documentation and point out that the core tools are not installed by default. I guess some others also struggled with this issue.  

For all other's who are experience this problem during the build just install the azure function core tools before running the build. In the nodejs case this can be simple done via yarn (or npm) `yarn gobal add  azure-functions-core-tools@2`
