### ISSUE TITLE
Function deployment with slot and SPN as deployment credential is not working

### ISSUE THREAD

**Issue by tiwarishub** [Azure/functions-action#65]
Hi Team, I am using azure function action and using slot name and SPN as deployment credentials. Here is my workflow
https://github.com/tiwarishub/samples/actions/runs/560242979/workflow 
![image](https://user-images.githubusercontent.com/64764738/107740816-fa97a780-6d31-11eb-8972-c4a738927ef2.png)

I am getting the below error
![image](https://user-images.githubusercontent.com/64764738/107740854-0b481d80-6d32-11eb-8831-35a5110dad25.png)

Here is a sample run with debug flag ``ACTIONS_STEP_DEBUG`` set to true https://github.com/tiwarishub/samples/runs/1885323454?check_suite_focus=true

I looked into the code and found that for this scenario, you are expecting Publish profile to present 
https://github.com/Azure/functions-action/blob/32a77f7af362fd0b21230d77d17a492673a6039c/src/handlers/parameterValidator.ts#L163
It has reference to `this._scmCredentials`. And this `scmCredentials`  with being set to default value https://github.com/Azure/functions-action/blob/32a77f7af362fd0b21230d77d17a492673a6039c/src/managers/builder.ts#L8
when publish profile is not present and in that URL is set to undefined . which is causing this issue

**Comment by 20shivangi** [comment]
@Hazhzeng @N-Usha Do we support slot deployment in function app for SPN auth?
It is not working when slot is specified and works only with Publish Profile auth. I checked the code this failure is there from start. There is no proper error message it fails in execution because of null reference.

**Comment by 20shivangi** [comment]
@Hazhzeng @N-Usha Please have a look at this issue

**Comment by 20shivangi** [comment]
As confirmed with @Hazhzeng ,  currently we don't have any plan to support it in SPN. Since publish profile is more secure (limited priviledge), so we only implement this feature in publish profile.
Please use `Publish Profile` when using slot deployment. We will look out for more such requests to have it in our backlog. Thanks

**Comment by ianmccaul** [comment]
I am not sure I understand the reasoning for this. When using a non-slotted deployment it doesnt require a publishing profile. Also, when using a webapp deployment it doesnt require a profile for slotted or non-slotted deployment. Why is the case of deploying a function to a slot via a service principal so different? This proves a problem for us specifically because we create the slot from the CI/CD workflow. But now we're left with 2 options.

1. We download the profile and store it in git as a secret. This is a manual process and these profiles get reset all the time, especially if you recreate function apps or slots. Also its different then any other type of deployment.
2. We use powershell to get the profile during the workflow and store it off. But you may ask what account we're using to get this profile. You guessed it, a service principal... This is even less ideal because we have to write some custom actions to solve this one specific arbitrary limitation, which is much more work to maintain in the end.

I would love to understand the reasoning behind why this one use case doesnt support that. I would disagree with this being closed.
